name: Create Azure AI Foundry Resources

on:
  workflow_dispatch:

jobs:
  create-azure-ai-foundry:
    env:
      REGION: "eastus2" # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: "none"

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

    #   - name: Azure Login
    #     uses: Azure/login@v2
    #     with:
    #       creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Temp fix
    #   - name: bicep tmp fix
    #     run: az config set bicep.use_binary_from_path=false

      - uses: cschleiden/replace-tokens@v1
        with:
            tokenPrefix: '__'
            tokenSuffix: '__'            
            files: '["infra/bicep/main.bicepparam"]'
        env:
            existingVnetName: ${{ secrets.VNET_RESOURCE_NAME }}            

      - uses: actions/upload-artifact@v4.6.2
        name: 'upload param files'
        with:
          path: infra/bicep/main.bicepparam
          
    #   - name: deploy
    #     id: createResources
    #     uses: azure/arm-deploy@v2
    #     with:
    #       subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #       scope: subscription
    #       region: ${{ env.REGION }}
    #       deploymentName: ${{ github.run_id }}
    #       template: ./infra/createEnv/main.bicep
    #       failOnStdErr: false
    #       parameters: ./infra/createEnv/main.bicepparam adminPassword=${{ secrets.VM_PASSWORD }} adminUserName=${{ secrets.VM_ADMIN }}        