name: Create Core Resources

on:
  workflow_dispatch:
    inputs:
      stateResourceGroupName:
        description: 'The name of the resource group that will contain the terraform state'
        required: true
        type: string        
        default: 'rg-tf-state'
      storageAccountName:
        description: 'The name of the storage account'
        required: true
        type: string
        default: 'strtfstatehg28'       
      containerName:
        description: 'The name of the container that will have the state'
        required: true
        type: string
        default: 'coretfstate'                    

jobs:
  create-core-resources:
    env:
      REGION: ${{ secrets.LOCATION }} # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: "none"

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.SP_FOUNDRY }}
          
      - uses: hashicorp/setup-terraform@v3
      
      - name: create terraform state        
        run: |
          az group create -n ${{ inputs.stateResourceGroupName }} -l ${{ secrets.LOCATION }}
          az storage account create --name ${{ inputs.storageAccountName }} --resource-group ${{ inputs.stateResourceGroupName }} --location ${{ secrets.LOCATION }} --sku Standard_LRS --kind StorageV2
          az storage container create --name ${{ inputs.containerName }} --account-name ${{ inputs.storageAccountName }} --account-key $(az storage account keys list --resource-group ${{ inputs.stateResourceGroupName }} --account-name ${{ inputs.storageAccountName }} --query "[0].value" -o tsv)