name: Build and Deploy Flight API

on:
  workflow_dispatch:

env:
  IMAGE_NAME: flight-api

jobs:
  build-deploy-image:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v4    

    - name: Azure Login
      uses: Azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build image
      run: |
        az acr login --name ${{ secrets.ACR_LOGIN_SERVER }} 
        az acr build -t ${{ secrets.ACR_LOGIN_SERVER }}/flight-api:${{ github.run_id }} -r ${{ secrets.ACR_LOGIN_SERVER }} .
      working-directory: ./src/apis/flight-api