name: Create Core Resources

on:
  workflow_dispatch:

jobs:
  create-azure-resources:
    env:
      REGION: ${{ secrets.LOCATION }} # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: "none"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Temp fix
      - name: bicep tmp fix
        run: az config set bicep.use_binary_from_path=false

    #   - uses: cschleiden/replace-tokens@v1
    #     name: Update bicepparam
    #     with:
    #         tokenPrefix: '__'
    #         tokenSuffix: '__'            
    #         files: '["infra/base/main.bicepparam"]'
    #     env:            
    #         location: ${{ secrets.LOCATION }}
    #         resourceGroupNameVNET: ${{ secrets.VNET_RESOURCE_GROUP_NAME }}
    #         resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
    #         subnetAgentAddressPrefix: ${{ secrets.SUBNET_AGENT_ADDRESS_PREFIX }}
    #         subnetJumpboxAddressPrefix: ${{ secrets.JUMPBOX_SUBNET_ADDRESS_PREFIX }}
    #         subnetPrivateEndpointAddressPrefix: ${{ secrets.SUBNET_PRIVATE_ENDPOINT_ADDRESS_PREFIX }}
    #         vnetAddressPrefix: ${{ secrets.VNET_ADDRESS_PREFIX }}
    #         apimSubnetAddressPrefix: ${{ secrets.SUBNET_APIM_ADDRESS_PREFIX }}
    #         publisherEmail: ${{ secrets.PUBLISHER_EMAIL }}
    #         publisherName: ${{ secrets.PUBLISHER_NAME }}

    #   - name: deploy
    #     id: createResources
    #     uses: azure/arm-deploy@v2
    #     with:
    #       subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #       scope: subscription
    #       region: ${{ env.REGION }}
    #       deploymentName: ${{ github.run_id }}
    #       template: ./infra/base/main.bicep
    #       failOnStdErr: false
    #       parameters: ./infra/base/main.bicepparam adminPassword=${{ secrets.VM_PASSWORD }} adminUserName=${{ secrets.VM_ADMIN }}

