name: Create Infra Workload

on:
  workflow_dispatch:

jobs:
  create-azure-resources:
    env:
      REGION: ${{ secrets.LOCATION }} # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: "none"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Temp fix
      - name: bicep tmp fix
        run: az config set bicep.use_binary_from_path=false

      - uses: cschleiden/replace-tokens@v1
        name: Update bicepparam
        with:
            tokenPrefix: '__'
            tokenSuffix: '__'            
            files: '["infra/workload/main.bicepparam"]'
        env:            
            location: ${{ secrets.LOCATION }}
            privateDnsRegistryResourceId: ${{ secrets.PRIVATE_DNS_REGISTRY_RESOURCE_ID }}
            privateEndpointSubnetResourceId: ${{ secrets.SUBNET_PRIVATE_ENDPOINT_ID }}
            workloadResourceGroupName: ${{ secrets.WORKLOAD_RESOURCE_GROUP_NAME }}
            subnetAcaResourceId: ${{ secrets.SUBNET_ACA_RESOURCE_ID }}
            vnetResourceGroupName: ${{ secrets.VNET_RESOURCE_GROUP_NAME }}
            privateDnsStorableTableResourceId: ${{ secrets.TABLE_STORAGE_PRIVATE_DNS_ZONE_RESOURCE_ID }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName: ${{ github.run_id }}
          template: ./infra/workload/main.bicep
          failOnStdErr: false
          parameters: ./infra/workload/main.bicepparam

      - uses: gliech/create-github-secret-action@v1
        with:
          name: ACA_ENVIRONMENT_RESOURCE_NAME
          value: ${{ steps.createResources.outputs.acaEnvironmentResourceName }}
          pa_token: ${{ secrets.PA_TOKEN }}          


      - uses: gliech/create-github-secret-action@v1
        with:
          name: ACA_ENVIRONMENT_RESOURCE_ID
          value: ${{ steps.createResources.outputs.acaResourceId }}
          pa_token: ${{ secrets.PA_TOKEN }}          
